import Foundation

struct MockData {
    static let featuredEvents: [Event] = [
        Event(
            id: "f1",
            title: "Jazz Under the Stars",
            venue: "Millennium Park",
            date: Calendar.current.date(byAdding: .day, value: 2, to: Date())!,
            time: "7:00 PM",
            price: "$45",
            imageURL: nil,
            category: .concerts,
            source: .api,
            tags: ["romantic", "music", "outdoors"],
            description: "An enchanting evening of jazz music under the open sky. Bring a blanket and enjoy world-class musicians in a beautiful park setting.",
            organizerName: nil,
            attendeeCount: nil,
            isVerified: false
        ),
        Event(
            id: "f2",
            title: "Couples Pottery Workshop",
            venue: "Clay & Craft Studio",
            date: Calendar.current.date(byAdding: .day, value: 3, to: Date())!,
            time: "2:00 PM",
            price: "$65",
            imageURL: nil,
            category: .classes,
            source: .api,
            tags: ["creative", "hands-on", "couples"],
            description: "Get your hands dirty together! Learn the basics of pottery in this beginner-friendly couples workshop.",
            organizerName: nil,
            attendeeCount: nil,
            isVerified: false
        ),
        Event(
            id: "f3",
            title: "Comedy Date Night",
            venue: "The Laugh Factory",
            date: Calendar.current.date(byAdding: .day, value: 1, to: Date())!,
            time: "8:30 PM",
            price: "$30",
            imageURL: nil,
            category: .comedy,
            source: .api,
            tags: ["funny", "nightlife", "date night"],
            description: "Laugh the night away with top comedians performing their best sets. Includes a complimentary drink for couples.",
            organizerName: nil,
            attendeeCount: nil,
            isVerified: false
        ),
        Event(
            id: "f4",
            title: "Sunset Kayaking",
            venue: "Lake Marina",
            date: Calendar.current.date(byAdding: .day, value: 4, to: Date())!,
            time: "5:30 PM",
            price: "$55",
            imageURL: nil,
            category: .outdoors,
            source: .api,
            tags: ["adventure", "water", "sunset"],
            description: "Paddle through calm waters as the sun sets. Tandem kayaks available for the perfect couples experience.",
            organizerName: nil,
            attendeeCount: nil,
            isVerified: false
        ),
        Event(
            id: "f5",
            title: "Hamilton",
            venue: "Civic Theater",
            date: Calendar.current.date(byAdding: .day, value: 7, to: Date())!,
            time: "7:30 PM",
            price: "$120",
            imageURL: nil,
            category: .theater,
            source: .api,
            tags: ["broadway", "musical", "special occasion"],
            description: "Experience the Tony Award-winning musical that has captivated audiences worldwide.",
            organizerName: nil,
            attendeeCount: nil,
            isVerified: false
        )
    ]

    static let tonightEvents: [Event] = [
        Event(
            id: "t1",
            title: "Open Mic Night",
            venue: "The Blue Room",
            date: Date(),
            time: "7:00 PM",
            price: "Free",
            imageURL: nil,
            category: .comedy,
            source: .api,
            tags: ["free", "casual", "live"],
            description: "An open mic night featuring local talent. Great for a spontaneous date.",
            organizerName: nil,
            attendeeCount: nil,
            isVerified: false
        ),
        Event(
            id: "t2",
            title: "Night Market",
            venue: "Downtown Square",
            date: Date(),
            time: "6:00 PM",
            price: "Free entry",
            imageURL: nil,
            category: .food,
            source: .api,
            tags: ["food", "shopping", "local"],
            description: "Browse local vendors, try street food from around the world, and enjoy live music.",
            organizerName: nil,
            attendeeCount: nil,
            isVerified: false
        ),
        Event(
            id: "t3",
            title: "Stargazing Session",
            venue: "Observatory Hill",
            date: Date(),
            time: "9:00 PM",
            price: "$15",
            imageURL: nil,
            category: .outdoors,
            source: .api,
            tags: ["romantic", "nature", "quiet"],
            description: "Join amateur astronomers for a guided tour of the night sky. Telescopes provided.",
            organizerName: nil,
            attendeeCount: nil,
            isVerified: false
        ),
        Event(
            id: "t4",
            title: "Acoustic Sessions",
            venue: "Vinyl Cafe",
            date: Date(),
            time: "8:00 PM",
            price: "$10",
            imageURL: nil,
            category: .concerts,
            source: .api,
            tags: ["music", "intimate", "cozy"],
            description: "Intimate acoustic performances in a cozy cafe setting. Perfect for music-loving couples.",
            organizerName: nil,
            attendeeCount: nil,
            isVerified: false
        )
    ]

    static let communityEvents: [Event] = [
        Event(
            id: "c1",
            title: "Couples Paint & Sip",
            venue: "Art Bar Studio",
            date: Calendar.current.date(byAdding: .day, value: 5, to: Date())!,
            time: "6:30 PM",
            price: "$40",
            imageURL: nil,
            category: .classes,
            source: .community,
            tags: ["art", "wine", "social"],
            description: "Paint a masterpiece together while enjoying wine and snacks. No experience needed!",
            organizerName: "Art Bar Studio",
            attendeeCount: 24,
            isVerified: true
        ),
        Event(
            id: "c2",
            title: "Salsa Dancing for Beginners",
            venue: "Dance Central",
            date: Calendar.current.date(byAdding: .day, value: 3, to: Date())!,
            time: "7:00 PM",
            price: "$25",
            imageURL: nil,
            category: .classes,
            source: .community,
            tags: ["dance", "active", "fun"],
            description: "Learn the basics of salsa dancing with your partner. Fun, energetic, and perfect for date night.",
            organizerName: "Dance Central Academy",
            attendeeCount: 18,
            isVerified: true
        ),
        Event(
            id: "c3",
            title: "Couples Cooking: Italian Night",
            venue: "Chef's Kitchen",
            date: Calendar.current.date(byAdding: .day, value: 6, to: Date())!,
            time: "6:00 PM",
            price: "$75",
            imageURL: nil,
            category: .food,
            source: .community,
            tags: ["cooking", "italian", "hands-on"],
            description: "Cook a full Italian dinner together with a professional chef guiding you step by step.",
            organizerName: "Chef Marco",
            attendeeCount: 12,
            isVerified: false
        ),
        Event(
            id: "c4",
            title: "Outdoor Movie Night",
            venue: "Riverside Park",
            date: Calendar.current.date(byAdding: .day, value: 2, to: Date())!,
            time: "8:00 PM",
            price: "Free",
            imageURL: nil,
            category: .outdoors,
            source: .community,
            tags: ["movie", "free", "outdoor"],
            description: "Bring a blanket and snuggle up for a classic movie under the stars. Popcorn provided!",
            organizerName: "Parks & Rec Dept",
            attendeeCount: 56,
            isVerified: true
        )
    ]

    static let quickDateIdeas: [QuickDateIdea] = [
        QuickDateIdea(id: "q1", emoji: "\u{2615}", title: "Coffee Date"),
        QuickDateIdea(id: "q2", emoji: "\u{1F3DE}", title: "Picnic"),
        QuickDateIdea(id: "q3", emoji: "\u{1F3AC}", title: "Movie Night"),
        QuickDateIdea(id: "q4", emoji: "\u{1F373}", title: "Cook Together"),
        QuickDateIdea(id: "q5", emoji: "\u{1F6B6}", title: "Sunset Walk"),
        QuickDateIdea(id: "q6", emoji: "\u{1F3AE}", title: "Game Night"),
        QuickDateIdea(id: "q7", emoji: "\u{1F4D6}", title: "Bookstore Date"),
        QuickDateIdea(id: "q8", emoji: "\u{1F9D8}", title: "Yoga Together"),
        QuickDateIdea(id: "q9", emoji: "\u{1F3A8}", title: "Museum Visit"),
        QuickDateIdea(id: "q10", emoji: "\u{1F3B5}", title: "Karaoke"),
        QuickDateIdea(id: "q11", emoji: "\u{1F374}", title: "Try New Restaurant"),
        QuickDateIdea(id: "q12", emoji: "\u{2B50}", title: "Stargazing")
    ]
}
